<tr>
    <td colspan=\"3\">2018-01-20 00:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>0</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 00:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>1</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 00:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>2</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 00:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>3</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 00:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>4</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 00:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>5</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 01:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>6</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 01:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>7</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 01:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>8</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 01:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>9</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 01:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>10</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 01:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>11</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 02:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>12</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 02:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>13</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 02:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>14</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 02:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>15</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 02:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>16</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 02:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>17</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 03:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>18</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 03:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>19</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 03:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>20</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 03:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>21</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 03:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>22</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 03:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>23</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 04:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>24</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 04:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>25</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 04:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>26</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 04:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>27</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 04:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>28</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 04:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>29</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 05:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>30</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 05:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>31</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 05:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>32</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 05:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>33</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 05:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>34</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 05:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>35</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 06:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>36</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 06:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>37</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 06:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>38</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 06:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>39</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 06:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>40</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 06:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>41</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 07:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>42</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 07:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>43</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 07:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>44</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 07:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>45</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 07:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>46</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 07:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>47</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 08:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>48</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 08:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>49</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 08:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>50</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 08:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>51</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 08:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>52</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 08:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>53</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 09:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>54</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 09:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>55</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 09:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>56</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 09:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>57</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 09:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>58</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 09:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>59</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 10:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>60</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 10:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>61</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 10:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>62</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 10:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>63</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 10:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>64</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 10:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>65</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 11:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>66</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 11:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>67</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 11:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>68</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 11:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>69</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 11:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>70</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 11:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>71</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 12:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>72</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 12:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>73</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 12:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>74</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 12:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>75</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 12:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>76</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 12:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>77</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 13:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>78</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 13:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>79</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 13:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>80</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 13:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>81</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 13:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>82</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 13:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>83</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 14:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>84</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 14:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>85</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 14:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>86</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 14:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>87</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 14:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>88</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 14:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>89</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 15:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>90</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 15:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>91</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 15:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>92</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 15:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>93</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 15:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>94</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 15:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>95</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 16:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>96</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 16:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>97</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 16:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>98</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 16:30:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>99</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 16:40:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>100</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 16:50:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>101</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 17:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>102</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 17:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>103</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 17:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>104</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 17:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>105</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 17:40:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>106</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 17:50:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>107</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 18:00:00</td>
    <td></td>
    <td>-</td>
    <td>0</td>
    <td>0</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>108</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 18:10:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>109</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 18:20:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>110</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 18:30:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>111</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 18:40:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>112</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 18:50:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>113</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 19:00:00</td>
    <td></td>
    <td>-</td>
    <td>0</td>
    <td>0</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>114</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 19:10:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>115</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 19:20:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>116</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 19:30:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>117</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 19:40:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>118</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 19:50:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>119</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 20:00:00</td>
    <td></td>
    <td>-</td>
    <td>4</td>
    <td>0</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>120</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 20:10:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>121</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 20:20:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>122</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 20:30:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>123</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 20:40:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>124</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 20:50:00</td>
<tr>
    <td>4</td>
    <td>10</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>125</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 21:00:00</td>
    <td></td>
    <td>-</td>
    <td>0</td>
    <td>10</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>126</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 21:10:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>127</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 21:20:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>128</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 21:30:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>129</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 21:40:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>130</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 21:50:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>131</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 22:00:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>132</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 22:10:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>133</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 22:20:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>134</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 22:30:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>135</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 22:40:00</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>136</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 22:50:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>137</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 23:00:00</td>
    <td>7</td>
    <td>10</td>
    <td>0</td>
    <td>0</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>138</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 23:10:00</td>
<tr>
    <td>6</td>
    <td>10</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>139</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 23:20:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>140</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 23:30:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>141</td>
</tr>
<tr>
    <td>9</td>
    <td>10</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>141</td>
</tr>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>141</td>
</tr>
<tr>
    <td>9</td>
    <td>10</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>141</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 23:40:00</td>
<tr>
    <td></td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>142</td>
</tr>
<tr>
    <td colspan=\"3\">2018-01-20 23:50:00</td>
<tr>
    <td>9</td>
    <td>10</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>-</td>
    <td>143</td>
</tr>"
